name: Bygg, test og deploy til dev/prod

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - 'LICENCE'
      - 'CODEOWNERS'
      - '.gitignore'
      - '.github/workflows/build-pr.yaml'
      - '.github/workflows/security.yaml'
      - '.github/workflows/alerts.yaml'
      - '.nais/alerts-dev.yaml'
      - '.nais/alerts-prod.yaml'
env:
  CI: true
  TZ: Europe/Oslo

jobs:
  bygg-test-push-image:
    permissions:
      contents: "read"
      id-token: "write"
    name: Bygg/test og push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Sjekker ut repo
        uses: actions/checkout@v3

      - name: Installerer node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installere pnpm
        uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Hente pnpm store mappe
        id: pnpm-cache
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setter opp pnpm cache for klient
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Setter opp pnpm cache for server
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('server/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Installerer dependencies
        run: pnpm install

      - name: Installerer dependencies for server
        run: cd server && pnpm install

      - name: Bygger applikasjonen
        run: pnpm run build

      - name: Bygger server
        run: cd server && pnpm run build

      - name: Bygg docker image
        uses: docker/setup-buildx-action@v2

      - name: Push docker image til Google Artifact Registry
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: okonomi
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          tag: latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

  deploy-dev-gcp:
    name: Deploy til dev-gcp
    needs: bygg-test-push-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          IMAGE: ${{ needs.bygg-test-push-image.outputs.image }}
          RESOURCE: .nais/naiserator-dev.yaml

  #  deploy-prod-gcp:
  #    name: Deploy til prod-gcp
  #    needs: deploy-dev-gcp
  #    if: github.ref == 'refs/heads/master'
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v3
  #      - uses: nais/deploy/actions/deploy@v1
  #        env:
  #          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
  #          CLUSTER: prod-gcp
  #          IMAGE: ${{ needs.bygg-test-push-image.outputs.image }}
  #          RESOURCE: .nais/naiserator-prod.yaml
