name: Digestabot Auto-merge

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 1"

env:
  TZ: Europe/Oslo

jobs:
  digestabot-automerge:
    permissions:
      contents: read
      pull-requests: write
    uses: navikt/mob-gha-workflows/.github/workflows/digestabot-automerge.yaml@main
    name: Digestabot Auto-merge
    secrets:
      APP_ID: ${{ vars.APP_ID }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
