name: Digestabot Update

on:
  schedule:
    - cron: "0 6 * * 1"
  workflow_dispatch:

env:
  TZ: Europe/Oslo

jobs:
  digestabot-update:
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    name: Digestabot Update
    uses: navikt/mob-gha-workflows/.github/workflows/digestabot-update.yaml@main
